# Generated by Django 3.2.9 on 2021-12-06 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_benefit'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='benefit',
            table='benefit',
        ),
    ]
